### ISSUE TITLE
False-Positives with CakePHP Plugins

### ISSUE THREAD

**Issue by ravage84** [composer-unused/composer-unused#108]
## Describe the bug
I used the plugin to check a CakePHP application that uses some CakePHP plugins and got two false-positives.

## Error dump
````
 Unused packages
 ✗ cakedc/tiny-mce
 ✗ muffin/footprint
````

## Additional information

``cakedc/tiny-mce`` is used in varous ways in ``src``:

- `` * @property \TinyMCE\View\Helper\TinyMCEHelper $TinyMCE``
- ``$this->addPlugin('TinyMCE');``
- ``public $helpers = ['TinyMCE.TinyMCE' => ['script' => '/js/tiny_mce4/tinymce.min.js']];``

I would expect this not be listed as unused package because of the ``@property`` usage.

``muffin/footprint`` is only loaded through CakePHP through  ``$this->addPlugin('Muffin/Footprint');``

I can understand why this is listed as not used.

**Comment by icanhazstring** [comment]
Hi @ravage84 thanks for reporting.

We have a multitude of problems here.

> * @property \TinyMCE\View\Helper\TinyMCEHelper $TinyMCE
This is related to #94. So this will be a feature to scan also annotations that the package is used.

> $this->addPlugin('TinyMCE');
> public $helpers = ['TinyMCE.TinyMCE' => ['script' => '/js/tiny_mce4/tinymce.min.js']];
> $this->addPlugin('Muffin/Footprint');
These are all problematic. As it is difficult to scan "strings" and compare them to any symbol a package provided.

This would be related to #69. As we would need to provide the possibility to "report" certain calls for `CakePHP` to be checked against the plugin that is required.

**Comment by icanhazstring** [comment]
While the first issue should be fairly easy to resolve.
The others might take a while as I am trying to provide this with the next version `0.8`

**Comment by ravage84** [comment]
@icanhazstring I totally understand your issues. I think scanning annotations would be worth it, especially those like ``@var``, ``@property`` etc.

But don't bother about the CakePHP plugins. If they are used only through the framework, I can ignore them. May be an exclude/ignore CLI parameter for the unused plugin would be nice.

**Comment by icanhazstring** [comment]
I will resolve the annotations parsing in the near future.
The others should then be solvable, but one would need to write a CakePlugin for composer-unused so usages can be parsed correctly 👍

**Comment by icanhazstring** [comment]
> May be an exclude/ignore CLI parameter for the unused plugin would be nice.

You actually can ignore packages using cli or even inside you `composer.json`

https://github.com/composer-unused/composer-unused#exclude-folders-and-packages
https://github.com/composer-unused/composer-unused#ignore-by-configuration

**Comment by icanhazstring** [comment]
annotation usage is fixed with #94 
Others can be ignored. Closing.
