### ISSUE TITLE
Packages only used in  composer.json commands are marked as unused

### ISSUE THREAD

**Issue by sadortun** [composer-unused/composer-unused#109]
## Describe the bug

```javascript
    "scripts": {
        "symfony-scripts": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters"
        ]
    }

```

**Comment by icanhazstring** [comment]
Hi @sadortun thanks for reporting.
I will mark this as duplicate to #43 which should be solved with #69.

**Comment by sadortun** [comment]
@icanhazstring Oops sorry about that, i did go through the list of issues, but for some reason i did not see it :) !

Awesome project BTW !!

**Comment by icanhazstring** [comment]
No worries 😉
And Thanks. Appreciate it 🙏
