### ISSUE TITLE
`--version` does not show the right version

### ISSUE THREAD

**Issue by c33s** [composer-unused/composer-unused#140]
## Describe the bug
version output does not match with the currently installed version.
```
php composer-unused.phar --version
Composer 1.9.1 2019-11-01 17:20:17
```
should be `0.7.1` (as you sadly require php 7.3 for higher versions)

**Comment by icanhazstring** [comment]
Hi @c33s, good point.
I do forget to update the version constant inside the code while tagging a new version.

Will see how I can automate that 👍

**Comment by glensc** [comment]
Also, it outputs nothing if there's no `composer.json` in current dir, leaving to believe the download is broken.

```
$ wget https://github.com/composer-unused/composer-unused/releases/download/0.7.5/composer-unused.phar
$ php composer-unused.phar --version
```

in some dir with composer.json:
```
$ php composer-unused.phar --version
You are running composer with Xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Composer 2.0-dev+source @release_date@
```

besides release date being not expanded, unclear where that version comes from, my system composer is 1.x:
```
$ composer --version
Composer version 1.10.19 2020-12-04 09:14:16
```

**Comment by icanhazstring** [comment]
@glensc composer gets shipped inside the phar bundle. So this is where the version is coming from when executing the phar.

This is also the reason for the non output if there is no composer.json present. I might improve this a bit and decouple the cli command from composer in the future.

But Thanks for bringing this up 👍
