### ISSUE TITLE
requiring a php in my lib leads to "Unused packages: php"

### ISSUE THREAD

**Issue by c33s** [composer-unused/composer-unused#142]
## Describe the bug
having a lib which simply requires a specific php version leads to `Unused packages: php`
`composer.yaml`

version 0.7.1 phar (cannot update your tool because higher versions require php7.3 which breaks my build matrix which checks against multiple php versions)

```yaml
name: c33s/utils
type: library
description: 'multiple small utils'
keywords: [ util, string, phar ]
license: MIT
autoload:
    psr-4: { C33s\Util\: 'src/' }
require:
    php: ">=7.1 || ^8.0"
```

`src/StringHelper.php`
```php
<?php

declare(strict_types=1);

namespace C33s\Util;

class StringHelper
{
    /**
     * Fake check if the current String could be a Regex.
     */
    public static function isRegex(string $string, string $regexCharacter = '/'): bool
    {
        return $regexCharacter === $string[0] && $regexCharacter === $string[-1];
    }
   ....
```

```bash
λ php.exe .robo/bin/composer-unused.phar -vvv

Box Requirements Checker
========================

> Using PHP 7.1.16
> PHP is using the following php.ini file:
  ...php.ini

> Checking Box requirements:
  ✔ The application requires the version ">=7.1" or greater.
  ✔ The application requires the extension "json".
  ✔ The package "composer/ca-bundle" requires the extension "openssl".
  ✔ The package "composer/ca-bundle" requires the extension "pcre".
  ✔ The package "nikic/php-parser" requires the extension "tokenizer".


 [OK] Your system is ready to run the application.


Running 1.9.1 (2019-11-01 17:20:17) with PHP 7.1.16 on Windows
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug

Loading packages
----------------

 1/1 [============================] 100% < 1 sec/< 1 sec 12.0 MiB

Scanning files from basedir ...utils
-----------------------------------------------------------------

 10/10 [============================] 100% < 1 sec/< 1 sec 20.0 MiB

Results
-------

Found 0 used, 1 unused and 0 ignored packages

 Used packages

 Unused packages
 ✗ php

 Ignored packages
```

**Comment by icanhazstring** [comment]
Hi @c33s, yes this is a known issue in the current version.

This only works currently if you require a package that requires php. I am working on a new mechanic to better Analyse used dependencies. But currently I don't have time to progress any further.

You can always try the `dev-0.8.x` version with parameter `-x`. This is the new feature, which is not nearly finished, but should provide the correct output for your current issue.

**Comment by c33s** [comment]
the main problem will be #141 as i don't assume that you backport the fix it will be a won't fix for me will it?

**Comment by SvenRtbg** [comment]
One could argue that this tool should never complain about PHP being unused. It could be filtered out right before emitting any results.

**Comment by icanhazstring** [comment]
@SvenRtbg which I totally understand but then again, there is the option to require php but never use it, because you only hold yaml configuration for symfony or other stuff.

But anyway. With 0.8.x this problem is solved. Since I do a major rewrite on the next version, 0.7 currently receives the more basic bug fixes.

**Comment by icanhazstring** [comment]
Merged into `main`. Will be released with next version.
Closing it for now.
