### ISSUE TITLE
Connection failure doesn't set failed exit code

### ISSUE THREAD

**Issue by bobvandevijver** [composer-unused/composer-unused#183]
## Describe the bug
Not much more than the issue title: the result code is 0 on a connection failure, while it shouldn't be. Although it does allow my pipelines to complete with todays fastly outage 😃

## Error dump
```
$ curl -JOLs https://github.com/icanhazstring/composer-unused/releases/latest/download/composer-unused.phar
$ php composer-unused.phar
connection failure
```

**Comment by icanhazstring** [comment]
Hi, thanks for reaching out.
I think this is based on the fact that composer 1 is still packaged in the phar.
Let me check.

**Comment by icanhazstring** [comment]
Just some questions:
- What composer version are you running?
- Are you using a correct github token (if any)?
- What PHP version are you running?

**Comment by bobvandevijver** [comment]
The runner image uses PHP 7.3.27 with Composer 2.0.11 and doesn't have access to any Github token. 

There is no lock file available, as that isn't persisted between the pipeline stages (but the vendor directory is fully present).

**Comment by bobvandevijver** [comment]
Hmm, I just tried to reproduce it in a container without a network interface without luck. It just ran and completed normally. So it might be that this was actually caused by something else...

**Comment by bobvandevijver** [comment]
Okay, so it seems that the curl command already failed and just retrieved a simple file with the text "connection failure" with a grand total of 18 bytes instead of the expected 4809k 😅

```
$ cat composer-unused.phar
connection failure
$ php composer-unused.phar
connection failure
```

I blame Fastly 🙄

**Comment by icanhazstring** [comment]
But anyways, thanks for letting me check again, so I can removed composer 1 support, as its not working with github anymore and is EOL ;)
