### ISSUE TITLE
Your github oauth token for github.com contains invalid characters: "ghp_XXX"

### ISSUE THREAD

**Issue by Slamdunk** [composer-unused/composer-unused#190]
Same as https://github.com/ergebnis/composer-normalize/issues/736

> The issue is in place when `composer-normalize` is used as a PHAR: it bundles `composer` due to its dependency to it, and the latest release for `composer-normalize` is dated on March, before Github introduced the new token formats and before `composer` fixed it in https://github.com/composer/composer/issues/9820
> 
> The solution should be to re-pack the PHAR distribution with the updated version of composer.

**Comment by icanhazstring** [comment]
Thanks for bringing this up @Slamdunk.

I will do a new release removing composer 1 support at all.
This should fix the problem.

**Comment by icanhazstring** [comment]
Hi @Slamdunk could you try to download 0.7.6?
I dropped composer v1 support, so that everything should be working again.
