### ISSUE TITLE
Doesn't suggest to remove library

### ISSUE THREAD

**Issue by webmake** [composer-unused/composer-unused#244]
## Describe the bug
I noticed that my composer.lock contains pagerfanta/core and pagerfanta/pagerfanta, (maybe due merge process or smth) I can freely remove by running:
`composer remove pagerfanta/pagerfanta` and it uninstalls, so wanted to test this library will it detect, reverted that both would exist, but `composer unused` didn't suggest at all removal.
Fragments from composer.lock
```
...
    "packages":
...
            "name": "pagerfanta/core",
            "version": "v2.7.2",
            "source": {
                "type": "git",
                "url": "https://github.com/Pagerfanta/core.git",
                "reference": "7fb7cacfb4916c9789e7a5999255214615218560"
            },
...         
    "packages-dev": [
...
            "name": "pagerfanta/pagerfanta",
            "version": "v1.1.0",
            "source": {
                "type": "git",
                "url": "https://github.com/BabDev/Pagerfanta.git",
                "reference": "8400ab498e500018cff9a099ac22555e7949aa9a"
            },
...
```

## Error dump
there is no error, only expected pagerfanta/pagerfanta to be presented.

## Additional information
php 7.4, composer 1.10.20
"icanhazstring/composer-unused": "^0.7.5"

**Comment by icanhazstring** [comment]
Hi @webmake 

composer-unused doesn't check the contents of your `composer.lock` as I assume you keep your `.json` and `.lock` in sync. This tool only checks for required but unused dependencies. So if these packages were not required anymore, this tool will produce no output.

**Comment by webmake** [comment]
Thank you for clarification
