### ISSUE TITLE
PHAR archive v0.7.8 require a PHP version ">= 7.4.0"

### ISSUE THREAD

**Issue by gander** [composer-unused/composer-unused#245]
## Describe the bug
A [phar archive](https://github.com/composer-unused/composer-unused/releases/download/0.7.8/composer-unused.phar) has been downloaded, the attempt to run it with an error about unsatisfied system requirements. Globally installed code works fine.

## Error dump
[composer-unused-dump.txt](https://github.com/composer-unused/composer-unused/files/7713033/composer-unused-dump.txt)

## Additional information
```
PHP 7.3.33 (cli) (built: Dec  2 2021 14:58:33) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.33, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.33, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v3.1.2, Copyright (c) 2002-2021, by Derick Rethans
```

**Comment by icanhazstring** [comment]
Hi @gander let me check on that, maybe the build is broken.

**Comment by icanhazstring** [comment]
Just release a new `0.7.9` bugfix release for 0.7.x branch which should fixes the phar build.

**Comment by gander** [comment]
```
I confirm that it now works for my PHP version.                                                                                           
```

**Comment by gander** [comment]
I confirm that it now works for my PHP version.
