### ISSUE TITLE
0.8.0-RC - composer-runtime-api requriement is detected as InvalidPackage that results in an error on markUsed method

### ISSUE THREAD

**Issue by AndreasA** [composer-unused/composer-unused#273]
## Describe the bug
If the composer.json contains a requirement to `composer-runtime-api` in combination with 0.8.0-RC it detects as invalid package instead of usedpackage and it then tries to call markUsed which fails as invalid package does not have a markused method.

## Additional information
PHP 8.1

**Comment by icanhazstring** [comment]
Thanks for bringing it up. Will take a look 👍

**Comment by icanhazstring** [comment]
Will release another RC soonish with the fix included

**Comment by VincentLanglet** [comment]
Hi @icanhazstring, why the `composer-runtime-api` was added to the ignored list ?

Shouldn't this "dependency" be added to the composer.json only if 
`Composer\InstalledVersions` is used ?
https://getcomposer.org/doc/07-runtime.md#installed-versions

https://github.com/maglnet/ComposerRequireChecker is reporting an error only if I use `Composer\InstalledVersions` without `composer-runtime-api` so I would expect this library to do the opposite and to reporte I can remove `composer-runtime-api` from the composer when I stopped using `Composer\InstalledVersions`. WDYT ?

**Comment by AndreasA** [comment]
@VincentLanglet Because it has nothing directly to do with InstalledVersions. that is just one aspect for which it can be used.

It actually checks that your composer installation uses the necessary runtime api, that one wants to use in the project.

see initial paragraph: https://getcomposer.org/doc/07-runtime.md#runtime-composer-utilities

InstalledVersion is just one part of it. There are other features, e.g. 2.x can be required to ensure the usage of composer 2.x 

Other parts are e.g. https://getcomposer.org/doc/07-runtime.md#autoloader-path-in-binaries

In the future it might even include more things.

with InstalledVersion composer-runtime-api is required in a certain version but that does not mean that other things do not require it as well.

It is also a simple way to require the usage of composer 2.x instead of 1.x.

**Comment by VincentLanglet** [comment]
> Though checking for all potential usages and keeping those up-to-date for the future would also be a solution but way more complicated.

This is what I would want, but I understand it would be way more complicated 😅
