### ISSUE TITLE
Multiple derprecations in php 8.1

### ISSUE THREAD

**Issue by beeyev** [composer-unused/composer-unused#283]
Hello, first of all, thanks for the great tool, I have been using it for quite a long time.  
But it seems that the library needs to be updated in order to work with PHP 8.1 
I get these errors:
```
Deprecated: Return type of HumbugBox3130\KevinGH\RequirementChecker\RequirementCollection::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/bin/composer-unused/.box/src/RequirementCollection.php on line 12

Deprecated: Return type of HumbugBox3130\KevinGH\RequirementChecker\RequirementCollection::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/bin/composer-unused/.box/src/RequirementCollection.php on line 16
```

Could you please fix that?

**Comment by icanhazstring** [comment]
Hi. Thanks for using it 😉
You are using the phar archive correct?
Will check on that.

**Comment by icanhazstring** [comment]
Related to https://github.com/box-project/box/issues/562#issuecomment-1004464177

**Comment by icanhazstring** [comment]
https://github.com/box-project/box/issues/586

**Comment by icanhazstring** [comment]
The box project was updated with a new phar. Probably only an update to the phive package and we should be fine.
Will check that later or you can give it a go using
```
phive update
```

Inside the project folder which should change the `.phive/phars.xml` with a new version for the box.
