### ISSUE TITLE
Google api client not found

### ISSUE THREAD

**Issue by ro0NL** [composer-unused/composer-unused#284]
From a global install

```
icanhazstring/composer-unused    0.8.0  
```

```
$ ~/.composer/vendor/bin/composer-unused

PHP Warning:  file_get_contents(/path/to/project/vendor/eo/honeypot-bundle/composer.json): failed to open stream: No such file or directory in composer-unused/src/Composer/LocalRepository.php on line 37
PHP Warning:  file_get_contents(/path/to/project/vendor/google/apiclient-services/../apiclient/src/Google/Client.php): failed to open stream: No such file or directory in composer-unused/symbol-parser/src/File/FileContentProvider.php on line 17

In IOException.php line 13:
                                                                                                                       
  Unable to open resource /path/to/project/vendor/google/apiclient-services/../apiclient/src/Google/Client.php  
```

Expected files are

- vendor/eo/honeypot-bundle/Eo/HoneypotBundle/composer.json
- vendor/google/apiclient/src/Client.php

am i missing something?

edit: the same happens from a local install btw

**Comment by icanhazstring** [comment]
Hi. Thanks for the report. Seems like an issue with autoload paths from one of those packages.

Will check.

Also keep in mind, global installation is not recommended and not supported.

**Comment by icanhazstring** [comment]
Thanks for the quick check. Will see to the dependencies

**Comment by filipagh** [comment]
Hi, i have similar problem with smarty 

```
PHP Warning:  file_get_contents(./vendor/smarty/smarty/libs/smarty_internal_data.php): Failed to open stream: No such file or directory in /srv/http/LiveAgent/LiveAgent/server/vendor/composer-unused/symbol-parser/src/File/FileContentProvider.php on line 17

In IOException.php line 13:
                                                                                
  Unable to open resource ./vendor/smarty/smarty/libs/smarty_internal_data.php  
                                                                                

```

**Comment by icanhazstring** [comment]
@ro0NL some problems I have found for documentation purpose:

- https://github.com/eymengunay/EoHoneypotBundle/blob/master/composer.json#L28
  - There might be an issue with the path resolving on my side
-  `expected vendor/google/apiclient/src/Client.php` is a wrong path should be `google/apiclient-services/src/...`
- Also I don't know there `/../apiclient/src/Google/Client.php` is coming from. Can you give your `composer.json`? (with removed confidential information)

@filipagh thanks for the smarty one, it seems to be missing a subfolder of `sysplugins`
Will check on that

**Comment by icanhazstring** [comment]
Ok, so news for `eo/honeypot-bundle`.
This package is using an deprecated configuration `target-dir` for composer which I did not implement.
So fixing this package should work if I implement the `target-dir` directory so the `composer.json` could be found.

**Comment by icanhazstring** [comment]
And the problem with google-api is this one
https://github.com/googleapis/google-api-php-client-services/blob/6692549efd68dfa84e0761e5e733d7aee09b7d50/autoload.php#L8

If they need the client, why is it not in their `required` section?
This does not make sense at all and is just a broken implementation. Don't know if can fix that.

**Comment by icanhazstring** [comment]
I have fixed an issue in `dev-main` to avoid getting into this
```
failed to open stream: No such file or directory in ...
```

However I need to implement a different approach to locate the package locally to actually resolve the problem.

**Comment by ro0NL** [comment]
HI @icanhazstring thanks for digging in :) i totally understand you don't implement outdated composer configuration :+1: 

i do think it's important for this command not to crash, and provide some form of meaningful output about what it "skips".

about the package from this "google" vendor (i've heard of them before /s), i just followed their README :) They do have a special autoloading trick: https://github.com/googleapis/google-api-php-client#cleaning-up-unused-services but im not sure it's relevant here.

Our refs:

```
google/apiclient          v2.12.1  Client library for Google APIs
google/apiclient-services v0.233.0 Client library for Google APIs
```

**Comment by icanhazstring** [comment]
Will do a skip if the require can't be loaded. Which will probably resolve in an unused package. But that should be fine for now 😉

**Comment by icanhazstring** [comment]
Should finish working in next release. Further improvements coming along the way :)

**Comment by icanhazstring** [comment]
@ro0NL the pathing issue with `eo/honeypot-bundle` should be fixed now in `dev-main`
