### ISSUE TITLE
Zombies Feature Yields Unexpected Results

### ISSUE THREAD

**Issue by gsteel** [composer-unused/composer-unused#286]
## Describe the bug

Version 0.8.0 on PHP 8.1 installed as a global dep, using `/usr/local/bin/composer-unused`

There are several packages that don't seem to be picked up any more - all of these are referenced in config files outside of the project psr root but otherwise unused in `my-project/src`. Previous versions picked these dependencies up from files in `my-project/config/*` _(I assume)_.

I decided to add theses false negatives to `[extra][unused]` and they all now appear in the newly added `Zombies` section when I would have assumed they'd end up in the `ignored` section.

The reason this is a bug to me is because the exit code is now non-zero so CI won't pass…

Am I doing something wrong?

_(It's my first time here, so thanks for this superb tool!! 😃)_

**Comment by icanhazstring** [comment]
Hi. Thanks for using 🤗
The zombie issue might be rwlted to #281 and will be fixed in next version.

The previous version picked up everything php related from the root of the project. This was some kind of difficult as some files were loaded that shouldn't have been loaded at all.

Additional file parsing will be added soon as well, so stay tuned

**Comment by gsteel** [comment]
Thanks @icanhazstring - Much appreciated.

**Comment by gsteel** [comment]
Can confirm that `dev-main` fixes the issue, but what's a bit odd is that now both unused and zombies are completely empty - I don't know if that's expected behaviour or not

**Comment by icanhazstring** [comment]
It does :)

Zombies are unused "excludes".
For example: You require a package `custom/javascript` which doesn not contain even php. Composer-unused will flag this dependency as `unused`.

If you want to tell composer-unused it should ignore that package you can call the binary with `--excludePackage=custom/javscript` or add it to `composer.json[extra][unused]`. This way the package won't be shown as unused and will simply be ignored.

After some time, you don't need `custom/javascript` anymore and simply remove it. Running composer-unused again will now tell you that `custom/javascript` is now a zombie exclusion as the dependency is no longer required.
