### ISSUE TITLE
[BUG] use of namespace not properly detected in v0.8.0

### ISSUE THREAD

**Issue by jkowalleck** [composer-unused/composer-unused#287]
## Describe the bug

in  version 0.8.0 of `composer-unused/composer-unused` a package is no longer detected as being used, , 
if the used symbols are made available from the original namespace.

in version 0.7.12 this behavior was es expected.

## Additional information

**_reproducible setup_** that displays the unexpected behaviour
(with `composer-unused` v0.7.12 and v0.8.0 in it):
 https://github.com/jkowalleck/composer-unused_issue287

example: 
```php
use Swaggest\JsonSchema;

class Foo
{
    public static function bar(JsonSchema\InvalidValue $error)
    {
        print_r($error); // for demo reasons.
    }
}
```

**Comment by icanhazstring** [comment]
Hi @jkowalleck thanks for the report.
The problem might be located here: https://github.com/composer-unused/symbol-parser/blob/main/src/Symbol/NamespaceSymbol.php#L29

Which comes down to this:
```
<?php

$use = 'Fubar\Test';
$class = 'Test\Class';

var_dump(strpos($class, $use)); // false
```

So this is most likely related to that and can be fixed in composer-unused/symbol-parser.
If you want you can give it a try :)

**Comment by jkowalleck** [comment]
>  If you want you can give it a try :)
will do.

**Comment by jkowalleck** [comment]
@icanhazstring , I had a look at it.
Dont think the [matcher](https://github.com/composer-unused/symbol-parser/blob/main/src/Symbol/NamespaceSymbol.php#L29) is broken, but the input to the matcher.

in a setup like this
```php
namespace Testing;

use My\NameSpace; // foreign package's namespace 
use B\NS\MyClass; // foreign 

class Foo extends MyClass implements NameSpace\Bar, \Other\Namespace\Baz {
}
```
i would expect to see the following symbols  as input to the matcher.
* `B\NS\MyClass`
* `My\NameSpace\Bar`
* `Other\Namespace\Baz`

instead i am seeing the following symbols as input to the matcher (in order):
* `My\NameSpace`
* `B\NS\MyClass`
* `MyClass`
* `Bar`
* `Other\Namespace\Baz`

a super wired example: https://3v4l.org/526JN
and i did not even use aliasing and other stuff.

**Comment by icanhazstring** [comment]
You are correct as I do use multiple strategies to extract symbols. Here you are encountering 3 of them.

- UseStrategy
- ExtendsStategy
- ImplementsStrategy

All of which result in a slight different symbol. But will give you some better information when I clam back home.

**Comment by icanhazstring** [comment]
Ok, so working with your code and this test you get the correct result which I am working with:

```
/**
 * @test
 */
public function itShouldParseCode(): void
{
    $code = <<<CODE
    <?php

    namespace Testing;

    use My\NameSpace1; // foreign package's namespace
    use B\NS\MyClass; // foreign

    class Foo extends MyClass implements NameSpace1\Bar, \Other\Namespace2\Baz {
    }
    CODE;

    $symbolNameParser = new SymbolNameParser(
        (new ParserFactory())->create(ParserFactory::ONLY_PHP7),
        new ConsumedSymbolCollector(
            [
                new UseStrategy(),
                new ExtendsParseStrategy(),
                new ImplementsParseStrategy(),
            ])
    );

    $symbols = iterator_to_array($symbolNameParser->parseSymbolNames($code));

    self::assertCount(5, $symbols);
}
```

This results in these symbols.
```
0 = "My\NameSpace1"
1 = "B\NS\MyClass"
2 = "MyClass"
3 = "NameSpace1\Bar"
4 = "Other\Namespace2\Baz"
```

**Comment by jkowalleck** [comment]
> As you would expect only 3 symbols to be provided.

this is an assumption that can be stretched.

having FQN at all times is the key to the solution, no matter how many they are. right?

**Comment by icanhazstring** [comment]
Yes would be. As the strpos solution of the matcher should work properly then. Also it will cut execution time immense if there are fewer symbols to check.

**Comment by jkowalleck** [comment]
this change is too complex for me, at the moment. requires to much reading into existing code and re-thinking some already implemented concepts.
meaning: will not implement a "fix" as it requires a design change. stopped working on this issue.

**Comment by icanhazstring** [comment]
OK. Thanks anyway for trying and sparing about. Will then take over 👍

**Comment by icanhazstring** [comment]
Fixed in `dev-main` will be included in next release

**Comment by jkowalleck** [comment]
> Fixed in `dev-main` will be included in next release

this will be the one after 0.8.1, right?

**Comment by jkowalleck** [comment]
> Fixed in `dev-main` will be included in next release

this will be the one _after_ 0.8.1, right, @icanhazstring ?

**Comment by icanhazstring** [comment]
Correct. 0.8.2 should be coming soon 😉
