### ISSUE TITLE
[BUG] unexpected "Zombie" for `composer-plugin-api` with `composer-unused:v0.8.0`

### ISSUE THREAD

**Issue by jkowalleck** [composer-unused/composer-unused#288]
## Describe the bug
The virtual composer package  `composer-plugin-api` 
is detected as a "Zombie" and theexitcode is non-`0` when running  `composer-unused:v0.8.0`.
This was no issue in  `composer-unused:v0.7.12`

## Additional information

according to the [docs of composer](https://getcomposer.org/doc/articles/plugins.md#creating-a-plugin) 
a plugin might describe its compatibility by requiring `composer-plugin-api`.
Therefore `composer-plugin-api` is a virtual composer package.

### expected

no issue, exit code 0 

### observed 

some error output, exit code 1

```text
Results
-------

Found 1 used, 0 unused, 0 ignored and 1 zombie packages

 Used packages
 ✓ php

 Unused packages

 Ignored packages

 Zombies exclusions (did not match any package))
 💀 composer-plugin-api
```

**Comment by icanhazstring** [comment]
Thanks. Zombie feature did not exist in 0.7.12.

But certain composer dependencies should be filtered out everytime and the filter should be flagged as used.

See here https://github.com/composer-unused/composer-unused/tree/main/tests%2FUnit%2FFilter

**Comment by icanhazstring** [comment]
@jkowalleck could it be, that you defined the exclusion yourself?

That would be that this exclusion is then being treated as a zombie.

**Comment by jkowalleck** [comment]
cood idea. need to take a look.

**Comment by jkowalleck** [comment]
false alarm, case closed
