### ISSUE TITLE
Incorrect Zombie Packages

### ISSUE THREAD

**Issue by MGatner** [composer-unused/composer-unused#291]
## Describe the bug
I seem to be getting reports on Zombie Packages that exists when excluded yet are "unused" when not excluded. Compare these two workflow runs:
* With exclusion (zombies): https://github.com/tattersoftware/codeigniter4-firebase/runs/5078326697?check_suite_focus=true
* Without exclusion (unused): https://github.com/tattersoftware/codeigniter4-firebase/runs/5078335880?check_suite_focus=true

**Comment by icanhazstring** [comment]
Seems weird. Will check 😉

**Comment by MGatner** [comment]
> Seems weird. Will check 😉

💪

**Comment by icanhazstring** [comment]
Maybe related to #282

**Comment by icanhazstring** [comment]
WIth latest `dev-main` ([9e79ecb](https://github.com/composer-unused/composer-unused/commit/9e79ecb3d1ec8b9d5b076678fc20b5c83c539d50)) this does not longer exist.

**Comment by MGatner** [comment]
Great news! I will have to wait for the release to percolate to the GitHub Actions setup but I will close this issue.
