### ISSUE TITLE
Crash happens if PSR-4 namespace has multiple folders

### ISSUE THREAD

**Issue by agustingomes** [composer-unused/composer-unused#293]
## Describe the bug
I Attempted the upgrade to the 0.8 version, and ran it via `vendor/bin/composer-unused`. But it would crash afterwards.

After analyzing the stack trace, it is caused by the `FileSymbolLoader` (in the `composer-unused/symbol-parser` upstream package) expecting the psr-4 namespace declaration to be string only, however, the composer specification allows for both, string and arrays, and therefore the example below would cause the application to crash:

```json
{
  "autoload": {
    "psr-4": {
      "My\\Namespace\\": ["config", "public", "src"],
      "Another\\Namespace\\": "libraries/message/src"
    }
  }
}

```

## Additional information
This failure can be caused in 2 places:
The method `partitionFilesAndFolders` and `resolvePackageSourcePath` since they assume the psr-4 paths would be exclusively string.

**Comment by icanhazstring** [comment]
Looking forward to the PRs. Thank you👌

**Comment by agustingomes** [comment]
I saw the root of this particular issue is in another library, but I'll try to come up with the PR's the following days

**Comment by agustingomes** [comment]
@icanhazstring I fixed this particular issue upstream in the PR https://github.com/composer-unused/symbol-parser/pull/25

**Comment by icanhazstring** [comment]
Fixed with https://github.com/composer-unused/symbol-parser/pull/25 and covered with #294
