### ISSUE TITLE
False positive unused `cdn77/test-utils`

### ISSUE THREAD

**Issue by simPod** [composer-unused/composer-unused#315]
## Describe the bug
I'm using `cdn77/test-utils` in tests (psr-4 dev-autoloaded)

```php
use Cdn77\TestUtils\Stub;

final class MyTest extends TestCaseBase
{
    public function testSth(): void
    {
        $a = Stub::create(A::class);
```

`composer-unused` says it's unused.

## Additional information

v0.8.1

**Comment by icanhazstring** [comment]
Hi @simPod.
Currently `require-dev` dependencies are not checked, as they should not be deployed to production.

So no need to see if there are used or not 😉

Or did I misunderstood something?

**Comment by simPod** [comment]
I'd also like to know about zombie dev dependencies from my project even though it's not production threatening 🙃  🧹

**Comment by icanhazstring** [comment]
Good point. Would you like to suggest a new feature request issue? 😉

So maybe a flag cli option which will enable dev dependency scan as well.

**Comment by simPod** [comment]
> Would you like to suggest a new feature request issue?

🤔 should I create new issue?

> So maybe a flag cli option which will enable dev dependency scan as well.

Depends what was the reason for excluding it in the first place, can tell. E.g. I expected it to be scanned by default.

**Comment by icanhazstring** [comment]
Problem with most dev dependencies is that they will mostly contain glue code which is not be able to be scanned or anything.

So enabling this by default will cause many users to have reports of many unused dependencies. So an optional flag will be the right way.

The initial idea was to avoid unused code in production to avoid security risks with unmaintained packages.

--
So yes, just create a new issue with some specs about having an option to scan dev dependencies 🙂

**Comment by simPod** [comment]
👌🏾

**Comment by simPod** [comment]
🤔 so I was thinking, why is dev dependency reported if dev-autoloaded sources are excluded?

**Comment by simPod** [comment]
Yup I explicitly went to check it a few moments ago that it sits in dev requirements section.

**Comment by icanhazstring** [comment]
Because I tried to reproduce it. And everything seems fine if my source code is using it. Everything is reported as used.
Especially if it is in `require-dev` the package is not even scanned.

I couldn't find a way to replicate the issue. Can you maybe setup a small repo replicating the exact problem so I can check against? Thanks.

**Comment by simPod** [comment]
Ok I'll try to isolate the issue.

**Comment by simPod** [comment]
Ok I'm dumb, it was in require, not dev :/ I looked into wrong project I guess.
