### ISSUE TITLE
False positive unused `php-http/logger-plugin`

### ISSUE THREAD

**Issue by simPod** [composer-unused/composer-unused#316]
## Describe the bug
I'm using `php-http/logger-plugin` in my project. Basically the same usage as in docs https://docs.php-http.org/en/latest/plugins/logger.html, directly instantiated.

`composer-unused` says it's unused.

## Additional information

v0.8.1

**Comment by icanhazstring** [comment]
Will check. Thanks.

**Comment by icanhazstring** [comment]
Found the issue. Fix coming :)
