### ISSUE TITLE
Progress bar missing

### ISSUE THREAD

**Issue by simPod** [composer-unused/composer-unused#320]
## Describe the bug
Is there a progress bar in v0.8? When I run the tool I see none.

(Also `-vvv` produces no output)

**Comment by icanhazstring** [comment]
Damn 🙈 

I totally removed this one due to the restructuring of the code. Will add it again. Sorry for that 😄

**Comment by MarcinGladkowski** [comment]
@icanhazstring #320 Review, plesase.

**Comment by MarcinGladkowski** [comment]
Hi! @icanhazstring Review, please https://github.com/composer-unused/composer-unused/pull/427

**Comment by icanhazstring** [comment]
Solves with #427
