### ISSUE TITLE
False positives after using `readonly` modifier

### ISSUE THREAD

**Issue by lcobucci** [composer-unused/composer-unused#326]
## Describe the bug

I'm changing one of my libs to require and use features from PHP 8.1.
After the [commit that introduces the `readonly` modifier](https://github.com/chimeraphp/routing/pull/289/commits/20b517f898d9d61ae211cad198e2849bffa4dd20), composer-unused started to report false positives.

I'm ignoring it for now but it might be good to investigate the cause :+1:

**Comment by icanhazstring** [comment]
Thanks for the report. I do actually have one task open an upstream library symbol-parser where I need to cover typed properties as well.

So seems like the tokenzier for readonly properties will have a different structure which I need to cover differently.

I will investigate it further down the line. Thanks for bringing it up 👍

**Comment by icanhazstring** [comment]
I have updated upstream `composer-unused/symbol-parser`.
Could you test again `dev-main` of the problem persists?

https://github.com/composer-unused/composer-unused/commit/9035d58f389282d218f68ec9b4b97b9f843e6184

**Comment by lcobucci** [comment]
@icanhazstring sorry about the delay.

I've built the `phar` using the latest commit and it indeed solved the issue, thanks :+1:

**Comment by lcobucci** [comment]
Could you use https://github.com/chimeraphp/routing?
Removing the ignored package makes `composer-unused` report the false positive https://github.com/chimeraphp/routing/blob/1.0.x/composer-unused.php#L8

As you can see on https://github.com/chimeraphp/routing/blob/1.0.x/src/Handler/ExecuteAndFetch.php#L9 that package is used and removing the `readonly` modifier from both properties makes `composer-unused` not report issues anymore.

**Comment by icanhazstring** [comment]
Got it. Will check

**Comment by icanhazstring** [comment]
One thing came to mind. Either the PHP_VERSION constant is not correct inside the phar and he is assuming php7. Or the execution runtime of the phar is not correct.

Can you check if you are running a php8.1 execution for the phar?

Because depending on that, the correct lexer ist used to parse the code.

**Comment by lcobucci** [comment]
I've built the phar using the `php8.1` service provided in this repo and ran the phar using PHP 8.1.

I've just changed the file in the `bin` folder to print `PHP_VERSION`, here's the output (check the first line):

```sh
$ php ../../composer-unused2 
8.1.3

Results
-------

Found 7 used, 2 unused, 0 ignored and 0 zombie packages

 Used packages
 ✓ php
 ✓ chimera/foundation
 ✓ fig/http-message-util
 ✓ psr/http-factory
 ✓ psr/http-message
 ✓ psr/http-server-handler
 ✓ psr/http-server-middleware

 Unused packages
 ✗ lcobucci/content-negotiation-middleware
 ✗ middlewares/negotiation

 Ignored packages

 Zombies exclusions (did not match any package)
```

**Comment by vudaltsov** [comment]
Any updates on this issue?

**Comment by simPod** [comment]
FYI I'm not using PHAR but composer dev dep as `icanhazstring/composer-unused` and have the same issue so it's not the PHAR issue I believe.

**Comment by icanhazstring** [comment]
@lcobucci can you check again with `0.8.3` as we added a fix for lexer so that readonly should work now.

**Comment by lcobucci** [comment]
@icanhazstring just tested, works like a charm. Thanks!

**Comment by simPod** [comment]
Yes, much awesome!
