### ISSUE TITLE
Bug: GitHub Output Not Applying Locally

### ISSUE THREAD

**Issue by MGatner** [composer-unused/composer-unused#328]
*See https://github.com/composer-unused/composer-unused/discussions/272#discussioncomment-2252393*

## Describe the bug
Supplying the `--output-format=github` argument in a local CLI does not apply GitHub formatting. Could be that `CiDetector` is overriding the argument?

## Additional information
Version: Latest `main` (c0a316db24f65f1cdfe5a39dbbfa84f3c087b5b2)
PHP:
```
PHP 7.4.10 (cli) (built: Sep  9 2020 06:36:14) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Xdebug v2.9.8, Copyright (c) 2002-2020, by Derick Rethans
    with Zend OPcache v7.4.10, Copyright (c), by Zend Technologies
```
OS: Ubuntu 20.04

**Comment by icanhazstring** [comment]
Thanks. Will check asap 👍

**Comment by icanhazstring** [comment]
Should be fixed in dev-main :)
