### ISSUE TITLE
Empty namespace in psr-4/0 will lead to error

### ISSUE THREAD

**Issue by icanhazstring** [composer-unused/composer-unused#342]
## Describe the bug
Using the namespace fallback from `composer.json` where you can use an `""` as namespace produces an error in 
https://github.com/composer-unused/composer-unused/blob/main/src/Command/Handler/CollectConsumedSymbolsCommandHandler.php#L59

We need to validate empty strings as well, maybe even skip them.

## Additional information
https://getcomposer.org/doc/04-schema.md#psr-4
https://getcomposer.org/doc/04-schema.md#psr-0

If you want to have a fallback directory where any namespace will be looked for, you can use an empty prefix like:
```
{
    "autoload": {
        "psr-4": { "": "src/" }
    }
}
```

**Comment by yoanmLf** [comment]
Hello 👋 

Indeed, I spent half a day trying to understand why 0.7 version was working fine while latest wasn't.
With latest version (`0.8.3`), every dependencies are marked as unused (except those which are a requirement for dependencies required by my project)

The quickest fix I found is to add `if ('' === $rootNamespace) { continue; }` just before [that](https://github.com/composer-unused/composer-unused/blob/02333ab878c9c53a84177f94456dff300e3eccc4/src/Command/Handler/CollectConsumedSymbolsCommandHandler.php#L58). 
As `strpos` will always return 0 if the needle is an empty space, it means the code basically removed every symbol found (therefore dependencies are marked as unused, as their symbols are removed from the list)

_That being said, it's the quickest fix **on your side**, but as a `composer validate` says, having an empty namespace is bad for performance, so quickest fix on projects side is actually to define each root namespaces instead._

Thanks for you work BTW 👌

**Comment by icanhazstring** [comment]
Yes, I am a bit struggling with that. But I think for now your suggestion would be a valid addition.
Maybe even check while loading the composer.json to see if there is an empty namespace defined and emit a warning from `composer-unused` itself with a link to composer docs.

Because right now it's really an edge case.
Would accept any PR in that direction and happily merge it :)

> Thanks for you work BTW 👌
Thanks for the appreciation. You're welcome :)
