### ISSUE TITLE
0.8.x: detects various used packages as unused

### ISSUE THREAD

**Issue by lazka** [composer-unused/composer-unused#346]
* git clone https://github.com/api-platform/api-platform
* cd api-platform/api
* composer install
* (add name in composer.json, see #345)
* composer-unused

Expected:

Marks all packages that provide classes referenced in `config/bundles.php` as used

Actual:

They are all marked as unused.

For example: `doctrine/doctrine-migrations-bundle` or `symfony/monolog-bundle`

This used to work with 0.7.x

**Comment by icanhazstring** [comment]
You need to configure additional places to be parsed using a custom configuration file.
In 0.7.x I scanned the whole directory beside the `composer.json` this had some advantages, but also a lot of drawbacks.

With 0.8.x composer-unused will primarily scan `composer.json` autoload directives first.
If you have any other file that uses dependencies outside this autoload scope, you need to configure that.

As an example you can use this:
https://github.com/composer-unused/composer-unused/blob/main/composer-unused.php

**Comment by lazka** [comment]
I see thanks, that wasn't really clear from reading the changelog. A Symfony example might be useful in the docs (/bin and /public also contain code)

**Comment by icanhazstring** [comment]
Will add something in the docs. Thanks :)

**Comment by rooselle** [comment]
I have same problem. With version 0.7 no package is marked as unused, even if for example symfony/mailer isn't used anywhere (and it isn't a requirement of any dependency). And with latest version, almost all Symfony packages are marked as unused.

I tried modifying the config with example file you gave, but that doesn't change anything (I tested a NamedFilter on one of the packages to be sure the config was taken into account and it is). A Symfony example would be much appreciated!

**Comment by icanhazstring** [comment]
> I have same problem. With version 0.7 no package is marked as unused, even if for example symfony/mailer isn't used anywhere (and it isn't a requirement of any dependency). And with latest version, almost all Symfony packages are marked as unused.
> 
> I tried modifying the config with example file you gave, but that doesn't change anything (I tested a NamedFilter on one of the packages to be sure the config was taken into account and it is). A Symfony example would be much appreciated!

Can you give me a small reproducible repository where I can test this to see what is going wrong?

**Comment by lazka** [comment]
```bash
composer create-project symfony/skeleton example-api
cd example-api
composer require --dev icanhazstring/composer-unused
./vendor/bin/composer-unused
```

**Comment by icanhazstring** [comment]
@lazka doing this will result in unused dependencies which is totally fine. As there are no source PHP files that are using these dependencies.

**Comment by OskarStark** [comment]
Hi,

I am facing the same issue, this is my config before in composer.json
```json
    "extra": {
        "symfony": {
            "allow-contrib": true,
            "require": "6.1.*"
        },
        "unused": [
            "datana-gmbh/doctrine-datetime-milliseconds-type",
            "ext-ctype",
            "ext-iconv",
            "ext-pdo_pgsql",
            "ext-redis",
            "league/commonmark",
            "league/html-to-markdown",
            "scienta/doctrine-json-functions",
            "symfony/flex"
        ]
    },
```

Now I switched to `composer-unused.php` with:
```php
<?php

declare(strict_types=1);

use ComposerUnused\ComposerUnused\Configuration\Configuration;
use ComposerUnused\ComposerUnused\Configuration\NamedFilter;
use Webmozart\Glob\Glob;

return static function (Configuration $config): Configuration {
    return $config
         ->addNamedFilter(NamedFilter::fromString('datana-gmbh/doctrine-datetime-milliseconds-type'))
         ->addNamedFilter(NamedFilter::fromString('ext-ctype'))
         ->addNamedFilter(NamedFilter::fromString('ext-iconv'))
         ->addNamedFilter(NamedFilter::fromString('ext-pdo_pgsql'))
         ->addNamedFilter(NamedFilter::fromString('ext-redis'))
         ->addNamedFilter(NamedFilter::fromString('league/commonmark'))
         ->addNamedFilter(NamedFilter::fromString('league/html-to-markdown'))
         ->addNamedFilter(NamedFilter::fromString('scienta/doctrine-json-functions'))
         ->addNamedFilter(NamedFilter::fromString('symfony/flex'))
    ;
};
```

What else do I need to add for a Symfony project? As this is my result now:
<img width="1095" alt="CleanShot 2022-06-28 at 09 30 52@2x" src="https://user-images.githubusercontent.com/995707/176120031-9072e8c2-4910-4b3e-8af8-c32e16ddec2f.png">

Thanks for your help!

**Comment by icanhazstring** [comment]
@OskarStark yes. Zombies are exclusions you configured but did not match any package your are using.

So just to clarify. You haven't had that many unused packages before updating to new version right?

What you can do as well, is adding additional paths to be scanned as well. The main difference between 0.7 and 0.8 is that 0.7 scanned the whole directory of you project, leading to haywire problems along the way.

That is why 0.8 is per default only scanning psr-0/4 directives from your composer.json. You can however add additional paths to the config which will be included. For symfony e.g. public/ and config/ or bin/

**Comment by OskarStark** [comment]
> @OskarStark yes. Zombies are exclusions you configured but did not match any package your are using.

> You haven't had that many unused packages before updating to new version right?

Yes

> What you can do as well, is adding additional paths to be scanned as well. The main difference between 0.7 and 0.8 is that 0.7 scanned the whole directory of you project, leading to haywire problems along the way.

Understand 👍 

> That is why 0.8 is per default only scanning psr-0/4 directives from your composer.json. You can however add additional paths to the config which will be included. For symfony e.g. public/ and config/ or bin/

That totally makes sense, but can you make an example? I mean how to scan those directories. AFAIK when using `setAdditionalFilesFor(...)` method, I need to provide a dependency/package 🤔

**Comment by OskarStark** [comment]
> Like this:

I did this:
```php
<?php

declare(strict_types=1);

use ComposerUnused\ComposerUnused\Configuration\Configuration;
use ComposerUnused\ComposerUnused\Configuration\NamedFilter;
use Webmozart\Glob\Glob;

return static function (Configuration $config): Configuration {
    return $config
         ->addNamedFilter(NamedFilter::fromString('datana-gmbh/doctrine-datetime-milliseconds-type'))
         ->addNamedFilter(NamedFilter::fromString('ext-iconv'))
         ->addNamedFilter(NamedFilter::fromString('ext-pdo_pgsql'))
         ->addNamedFilter(NamedFilter::fromString('ext-redis'))
         ->addNamedFilter(NamedFilter::fromString('league/commonmark'))
         ->addNamedFilter(NamedFilter::fromString('league/html-to-markdown'))
         ->addNamedFilter(NamedFilter::fromString('symfony/flex'))
        ->setAdditionalFilesFor('icanhazstring/composer-unused', [
            __FILE__,
            ...Glob::glob(__DIR__ . '/public/*.php'),
        ])
        ->setAdditionalFilesFor('icanhazstring/composer-unused', [
            __FILE__,
            ...Glob::glob(__DIR__ . '/bin/*.php'),
        ])
        ->setAdditionalFilesFor('icanhazstring/composer-unused', [
            __FILE__,
            ...Glob::glob(__DIR__ . '/tests/*.php'),
        ])
            ->setAdditionalFilesFor('icanhazstring/composer-unused', [
            __FILE__,
            ...Glob::glob(__DIR__ . '/templates/*.php'),
        ])
        ->setAdditionalFilesFor('icanhazstring/composer-unused', [
            __FILE__,
            ...Glob::glob(__DIR__ . '/config/*.php'),
        ]);
};
```

But Do I need to add the glob for every dependency where it is used?

**Comment by OskarStark** [comment]
I tried
```php
        ->setAdditionalFilesFor('symfony/process', [
            __FILE__,
            ...Glob::glob(__DIR__ . '/bin/*.php'),
        ])
```

Which works and now `symfony/process` is not unused anymore

**Comment by icanhazstring** [comment]
Your application also counts as "package". It's the root package actually. So you have to use the "name" from your composer.json

**Comment by OskarStark** [comment]
AH that's the trick!

**Comment by OskarStark** [comment]
So this should work, right?
```php
        ->setAdditionalFilesFor('datana-gmbh/cockpit', [
            __FILE__,
            ...array_merge(
                Glob::glob(__DIR__ . '/bin/*.php'),
                Glob::glob(__DIR__ . '/config/*.php'),
                Glob::glob(__DIR__ . '/public/*.php'),
                Glob::glob(__DIR__ . '/templates/*.php'),
            ),
        ]);
```

**Comment by icanhazstring** [comment]
Should work, yes 😉

**Comment by OskarStark** [comment]
Unfortunately I get the same result :-( 
<img width="676" alt="CleanShot 2022-06-28 at 09 57 27@2x" src="https://user-images.githubusercontent.com/995707/176125549-677cd065-646c-4a14-bb23-d96fc3f1b44e.png">

**Comment by OskarStark** [comment]
I pinged you on Slack 😄

**Comment by simPod** [comment]
Ok my issue is related to https://github.com/composer-unused/composer-unused/issues/326 I guess.

**Comment by icanhazstring** [comment]
> I also have problems with falsy unused packages. Let's say there are bundles that are not used in my code anywhere besides registering in `config/bundles.php`. I want to to tel Composer Unused to look there. How do I do that? Unfortunately I can't understand README instructions. Or I understand but does it mean I have to call `setAdditionalFilesFor` for all falsy unused packages? Maybe Composer Unused config should have option to just set additional dir (or file) to scan?

If this is a missing source for your app. You need to pass in the name of your app along with the paths you want to add.

**Comment by icanhazstring** [comment]
As we did more improvements about how additional packages/folders are scanned, I am closing this issue for now, as it accumulates multiple different issues right now.

If you have a specific problem still unsolved, feel free to open a new issue.
