### ISSUE TITLE
Undefined property: __ComposerUnused__\PhpParser\Node\Expr\Variable::$value

### ISSUE THREAD

**Issue by gemal** [composer-unused/composer-unused#347]
`Notice: Undefined property: __ComposerUnused__\PhpParser\Node\Expr\Variable::$value in phar://app/composer-unused.phar/vendor/composer-unused/symbol-parser/src/Parser/PHP/FileInclude.php on line 24`

when I run `php composer-unused.phar`

```
php composer-unused.phar --version
composer-unused 0.8.2
```

```
php -v
PHP 7.4.27 (cli) (built: Dec 14 2021 19:52:13) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
```

**Comment by icanhazstring** [comment]
Hi. Thanks for the report.
Since this is a PHP Parser problem it is hard to tell what went wrong.

Can you isolate the problem to a certain dependency or your own code?

**Comment by icanhazstring** [comment]
This probably has to do something with `require` or `include` (also l the `_once` variation) and a concatenation of the path.

**Comment by icanhazstring** [comment]
Related to https://github.com/composer-unused/symbol-parser/issues/86
Silently solved.
