### ISSUE TITLE
Support for Symfony 4.4 is broken

### ISSUE THREAD

**Issue by Jean85** [composer-unused/composer-unused#358]
## Describe the bug
Support for Symfony 4.4 is broken, probably because there's no `--prefer-lowest` CI job to check it. Main stopper for now is this one:
> Fatal error: Uncaught Error: Call to undefined function Symfony\Component\DependencyInjection\Loader\Configurator\service() in /var/www/infacile/vendor/icanhazstring/composer-unused/config/services.php on line 32
>
> Error: Call to undefined function Symfony\Component\DependencyInjection\Loader\Configurator\service() in /var/www/infacile/vendor/icanhazstring/composer-unused/config/services.php on line 32

## Additional information
`service()` function is a rename of the previous `ref()` function in Symfony DI PHP DSL, introduced in 5.1: https://github.com/symfony/symfony/commit/366405b93d670555079605422c5fd05cda23ee08

**Comment by icanhazstring** [comment]
Thanks for the report.

This particular problem might be fixable using `methods_exists` on the `$configurator` in `config/services.php`.
So that symfony 4.4 for that part is working.

Other than that, a build with `--prefer-lowest` should be added :)
