### ISSUE TITLE
Feature: Interactive remove of unused packages

### ISSUE THREAD

**Issue by icanhazstring** [composer-unused/composer-unused#37]
After listing the unused packages, there should be an interactive mode to remove unused packages.

**Describe the solution you'd like**
After finding unused packages the user should get asked what to do with unused packages:
- remove
- skip
- ignore (should be added to `composer.json` `extra` for ignore)

**Additional information**
This kind of behavior should be optional and might be enabled with a cli parameter `--interactive`. Using an opt-in parameter this should not interfere with CI usage of this tool.

**Comment by Borumer** [comment]
I am interested in taking up this issue. I am a new contributor to this repository.

**Comment by icanhazstring** [comment]
Hi @Borumer, sure go ahead.
If you need any help or more information, don't hesitate to ask :)

**Comment by Borumer** [comment]
@icanhazstring So I'm looking in `UnusedCommand.php` and I figured out that the `addOption()` method is what is needed here. But all the options currently set use arguments, not interaction. How would I go about using an interactive command? This is the code that I have so far:

        $this->addOption(
            'interactive',
            null,
            InputOption::VALUE_OPTIONAL,
            "Choose between remove, skip, and ignore"
        );

Also, do you want it to be asked for each package?

**Comment by icanhazstring** [comment]
Yes, the option is the correct one.

How the workflow should be:

1. The user enables the interactive mode using `--interactive`.
After the scan is done the user should be asked which packages to remove.
https://github.com/composer-unused/composer-unused/blob/75c35a0a3671bb5726e649a400e7269a033fc060/src/Command/UnusedCommand.php#L200

2. For this at the above-mentioned line, iterate over the `$unusedPackages` again and ask for each package if the user wants it to be removed, ignored, or skipped. This can be done using a `ChoiceQuestion` from `symfony/console` (which is already installed)
Also see here for the docs: https://symfony.com/doc/current/components/console/helpers/questionhelper.html#let-the-user-choose-from-a-list-of-answers

3. Different outcomes:
  a. Using `skip` nothing is done to the package and it will be left as is.
  b. `ignore` should add a section into the `composer.json` from the root project adding a new entry into the `extras.unused` array. (see https://github.com/composer-unused/composer-unused#ignore-by-configuration)
  c. With `remove` every package name (e.g.: `vendor/package`) should be saved into a new array using only the names

4. Remove possible items from the "remove array" using the `composer remove` command.
This should be possible by using `$this->getApplication()` and triggering the `composer remove` command with every package. For example this should be the command triggered:
`composer remove vendor1/package vendor2/package ...`

**Comment by icanhazstring** [comment]
No active need right now.
