### ISSUE TITLE
New composer platform dependency (since composer 2.2) not detected

### ISSUE THREAD

**Issue by AndreasA** [composer-unused/composer-unused#381]
## Describe the bug
Since composer 2.2 it is now possible to target the composer version directly using the `composer` platform dependency.

See https://getcomposer.org/doc/articles/composer-platform-dependencies.md#composer-package-composer

However, it is not yet added to the always used packages https://github.com/composer-unused/composer-unused/blob/0.8.2/src/Filter/FilterCollection.php#L22 and though it does not result in an error it cannot be resolved.

Probably enough to just add it to the list https://github.com/composer-unused/composer-unused/blob/0.8.2/src/Filter/FilterCollection.php#L22 here.

**Comment by icanhazstring** [comment]
Good point. Feel free to add a PR with some Tests. Happy to merge it 🙏👍
