### ISSUE TITLE
Package marked as used by "required-by" even if other package is unused

### ISSUE THREAD

**Issue by icanhazstring** [composer-unused/composer-unused#395]
Seems like `composer-unused` is marking a package as `used` (with required-by) even if the other packages requiring the first one is marked as `unused`.

Current output:
```
Results
-------

Found 1 used, 1 unused, 0 ignored and 0 zombie packages

 Used packages
 ✓ a/a (required by: b/b)

 Unused packages
 ✗ b/b
```

Expected output:
```
Results
-------

Found 0 used, 2 unused, 0 ignored and 0 zombie packages

 Used packages

 Unused packages
 ✗ a/a
 ✗ b/b
```

**Comment by MarcinGladkowski** [comment]
Hi!

I want to say I really like this package source code, style of coding. The implementation is very interesting.  It's my first time with tool based on parsing source code/AST , that's why I'm very into resolving issues/bugs etc. Thanks and Good job!

**Comment by icanhazstring** [comment]
Hi @MarcinGladkowski.

Welcome 🎉
Thank you for your contribution. Glad you like this tool and are willing to contribute. I really do appreciate it. 🙏

**Comment by MarcinGladkowski** [comment]
Thanks @icanhazstring . If you mark issues with proper labels, I will do it pleasantly.
