### ISSUE TITLE
Don't report Github output when package ignored

### ISSUE THREAD

**Issue by samsonasik** [composer-unused/composer-unused#397]
## Describe the bug

In rector-src, the composer-unused is added with ignore `rector/*` prefix:

```php
use ComposerUnused\ComposerUnused\Configuration\Configuration;
use ComposerUnused\ComposerUnused\Configuration\PatternFilter;

return static function (Configuration $config): Configuration {
    // rector dependencies
    $config->addPatternFilter(PatternFilter::fromString('#rector/.#'));

    return $config;
};
```

However, in github view files, it show the github output notice:

![Screen Shot 2022-10-04 at 15 09 56](https://user-images.githubusercontent.com/459648/193768164-f7d9a206-6cc1-4563-9147-3b3c4fa50a50.png)

I think it should not be shown when it already ignored.

**Comment by icanhazstring** [comment]
Yes, you are correct. This is clearly a bug and should be checked in the `GithubFormatter`.

Also, there might be an issue with the `partition` from unused to ignored dependencies here:
https://github.com/composer-unused/composer-unused/blob/main/src/Console/Command/UnusedCommand.php#L228-L242

This should remove ignored packages from unused ones, so they actually should not be printed out by the OutputFormatter.
I got a slight suspicion that the PatterFilter does not work correctly here.

**Comment by icanhazstring** [comment]
On the other hand. I think ignored packages should not be `warning` level output 🤔
Don't know what might be the best solution here.

Remove the output altogether for github actions, or mark it as `info`?
What do you think?

**Comment by samsonasik** [comment]
I don't know what the right solution is, on console output, showing list of ignored package seems ok, but I think it should not be shown in github view files output tab

**Comment by samsonasik** [comment]
@icanhazstring it seems resolved by using `--output-format default` so it does not appear on github view files, ref https://github.com/rectorphp/rector-src/commit/f8e42e16e1f153548d727bda550330ceeca223a5#r85780390

**Comment by icanhazstring** [comment]
But be aware, that "finding" errors (unused dependencies) now requires you to open the build log for that action. So it might be a little inconvenient :)
