### ISSUE TITLE
`--excludeDir` is ignored

### ISSUE THREAD

**Issue by mvhirsch** [composer-unused/composer-unused#418]
## Describe the bug
I try to scan a very large project, with even larger files in it. It takes a long time, without doing anything. Is there a `--debug` option to see, which files are scanned right now? `-vvv` won't do anything, too.

After looking at the command I noticed `--excludeDir`, but I can't find any code handling it.

**Comment by icanhazstring** [comment]
Hm. That seems like a bug if that is not working anymore. Maybe I even missed it from 0.7 to 0.8 😱
