### ISSUE TITLE
Wrong version in command

### ISSUE THREAD

**Issue by ssanko** [composer-unused/composer-unused#420]
There is a wrong version number in command

https://github.com/composer-unused/composer-unused/blob/af9085d2058333d26559b334c536c40fb04e28d3/src/Console/Command/UnusedCommand.php#L33

**Comment by icanhazstring** [comment]
True, thanks. If you want you can just increase it to the next one (0.8.5) with a PR . I am happy to merge it 🙂

Otherwise I will do it if I find the time.
