### ISSUE TITLE
Possible false-positive

### ISSUE THREAD

**Issue by icanhazstring** [composer-unused/composer-unused#462]
### Discussed in https://github.com/composer-unused/composer-unused/discussions/461

<div type='discussions-op-text'>

<sup>Originally posted by **tvdijen** March 16, 2023</sup>
Hi!

I'm new to this package, so maybe I'm doing something wrong, but I may have hit a bug.
Hopefully you can help me identify if it's a bug or misuse.

My project `simplesamlphp/simplesamlphp` has a hard [dependency](https://github.com/simplesamlphp/simplesamlphp/blob/master/composer.json#L69) on `simplesamlphp/assert`.
It is used in _many_ places around the project, for instance [here](https://github.com/simplesamlphp/simplesamlphp/blob/master/src/SimpleSAML/Session.php#L716), and [here](https://github.com/simplesamlphp/simplesamlphp/blob/master/src/SimpleSAML/Stats.php#L78.

The thing is, this action reports it as being [unused](https://github.com/simplesamlphp/simplesamlphp/actions/runs/4441263980/jobs/7796122928#step:10:11). What am I doing wrong?

Thanks!</div>

---

First checks don't indicate a real problem.
psr-4 autoload of both the root and dependency package is good.

**Comment by tvdijen** [comment]
You think this is worth a new tag? :person_with_pouting_face:

**Comment by tvdijen** [comment]
No, this was merged two days after :)  Thanks for checking

**Comment by icanhazstring** [comment]
Tagged with 0.8.8 :)
