### ISSUE TITLE
Add ability to define source/vendor dir outside composer.json

### ISSUE THREAD

**Issue by icanhazstring** [composer-unused/composer-unused#470]
### Discussed in https://github.com/composer-unused/composer-unused/discussions/400

<div type='discussions-op-text'>

<sup>Originally posted by **CDRO** October  5, 2022</sup>
In some cases, as in TYPO3, packages are not always installed in `vendor/<vendor>/<package>` as it would be expected by the plugin, in this case an error appears quickly and no scan is done.

To test this, simply execute this and run `composer-unused.phar` in the directory you just created:
```bash
composer create-project typo3/cms-base-distribution:^11 example-project-directory
```

As TYPO3 will probably shift all packages to the vendor folder in version 12 or 13 anyway, this might not be a problem in the future anymore, but regarding one of the the goals (helping remove packages before you upgrade, so you don't keep it around for nothing), this would probably be a game changer for the TYPO3 dev community, if it would work as expected 💪 </div>

---

Users of composer-unused should be able to define the vendor dir (by default inferred using composer.json defaults).
This helps users of typo3 or other frameworks to tell composer-unused where to look for consumed or defined symbols.

This could be placed into the `composer-unused.php` configuration.

Besides providing this ability, some more additions are needed to actually provide functionality for that.
E.g.
- currently, packages take their sources directly from `baseDir . vendor` which might not work in typo3 especially

**Comment by MarcinGladkowski** [comment]
PR https://github.com/composer-unused/composer-unused/pull/522
