### ISSUE TITLE
Generate version and release date during release

### ISSUE THREAD

**Issue by icanhazstring** [composer-unused/composer-unused#489]
Currently the version is hardcoded into the console command.

Would be nice to read the version from a file generated at release action and read the version from there.

Idea would be to just use the tag, which is already used to upload the phar, to be put in some kind of PHP formatted file which just returns an array with `version` and `releaseDate`.

When running `bin/composer-unused --version` this information can be printed out.

**Comment by llaville** [comment]
I've myself be in face of this issue in past ! 
Here are how I solved it (it's a suggestion) in my projects : `php-compatinfo`, `php-compatinfo-db`

From my Console Symfony Application

- https://github.com/llaville/php-compatinfo-db/blob/master/src/Presentation/Console/Application.php#L119-L122

I used a wrapper around [Composer runtime utility](https://getcomposer.org/doc/07-runtime.md#installed-versions) 

- https://github.com/llaville/php-compatinfo-db/blob/master/src/Infrastructure/Framework/Composer/InstalledVersions.php

Dummy use case

```json
{
    "require": {
        "bartlett/php-compatinfo-db": "^5"
    }
}
```

Sample script to demonstrate usage 

```php
<?php

use Bartlett\CompatInfoDb\Infrastructure\Framework\Composer\InstalledVersions;

require_once __DIR__ . '/vendor/autoload.php';

function getInstalledVersion(bool $withRef = true): ?string
{
    return InstalledVersions::getPrettyVersion('bartlett/php-compatinfo-db', $withRef);
}

var_dump(['with hash ref' => getInstalledVersion(true)]);
var_dump(['without hash ref' => getInstalledVersion(false)]);

```

Will echo such output

```text
array(1) {
  ["with hash ref"]=>
  string(13) "5.4.0@b5941db"
}
array(1) {
  ["without hash ref"]=>
  string(5) "5.4.0"
}
```

When I reused it on `php-compatinfo` (console application : https://github.com/llaville/php-compatinfo/blob/6.5/src/Presentation/Console/Application.php#L186), it will give 
either from source file or from PHAR distrib : https://github.com/llaville/php-compatinfo/releases/download/6.5.5/phpcompatinfo.phar

```
phpCompatInfo version 6.5.5 DB version 4.11.0

Usage:
  command [options] [arguments]
```

NB: `4.11.0` is an older version of compatinfo-db PHP 7.4 compatible, while `5.4.0` is for PHP 8.0 or greater

**Comment by icanhazstring** [comment]
Nice idea thanks. Will check on that 👍

**Comment by llaville** [comment]
Another quick solution is to use like this : https://github.com/bmitch/churn-php/blob/master/bin/app.php#L10-L18

**Comment by icanhazstring** [comment]
Thanks for all the suggestions @llaville. Really helps 🙏

**Comment by llaville** [comment]
@icanhazstring Regression detected : Your solution with GitHub Workflow is incompleted !

The solution is based on a local `.version` file. But this file is only generate by  `validate-phar.yml` (see https://github.com/composer-unused/composer-unused/blob/21654deeeec8d94c5bd4ce2c2e46bda7ad369e12/.github/workflows/validate-phar.yml#L46-L47) and not `release-phar.yml` (see https://github.com/composer-unused/composer-unused/blob/fd2624f49de2d8925355cfb8739e2b2a57017d10/.github/workflows/release-phar.yml)

Confirmed by the latest version 0.8.10 (https://github.com/composer-unused/composer-unused/releases/download/0.8.10/composer-unused.phar) that still identify 0.8.7 version

```
composer-unused.phar --version

```

**Comment by llaville** [comment]
@icanhazstring did you missed my previous comment https://github.com/composer-unused/composer-unused/issues/489#issuecomment-1774634283 ?

**Comment by icanhazstring** [comment]
Hi @llaville, no I did not miss it.
But I am currently occupied with other stuff where I can't really work on this.

If you might be so kind to just either reopen or create a new Ticket with that :)
I would also be happy to accept any PR to solve this issue.
