### ISSUE TITLE
Add polyfill for `ext-ds`

### ISSUE THREAD

**Issue by icanhazstring** [composer-unused/composer-unused#507]
### Discussed in https://github.com/composer-unused/composer-unused/discussions/506

<div type='discussions-op-text'>

<sup>Originally posted by **llaville** May  6, 2023</sup>
Hello,

As you used [`ext-ds`](https://pecl.php.net/package/ds), as development requirement, since relase [0.7.4](https://github.com/composer-unused/composer-unused/releases/tag/0.7.4) , I suggest to add the [Polyfill](https://github.com/php-ds/polyfill).

```json
    "require-dev": {
        "ext-ds": "*",
        "php-ds/php-ds": "^1.4",
    },
```
If extension is available, the polyfill won't be used, and if polyfill is installed, that will avoid following error during installation !

This will enhance User Experience, rather than to get, when running `composer install` (because the lock file included the extension)

![ext-ds_missing](https://user-images.githubusercontent.com/364342/236602571-bcff10fc-2a5e-4fc3-b9a6-38ea8f195a7a.png)

Even, if we can avoid this with Composer tip 

```
Alternatively, you can run Composer with `--ignore-platform-req=ext-ds` to temporarily ignore these required extensions.
```

What do you think ?
</div>

**Comment by llaville** [comment]
When this package is installed with `composer install --ignore-platform-req=ext-ds` command, and we just follow to check if all seems good : `composer check`  (see https://github.com/composer-unused/composer-unused/blob/0.8.7/composer.json#L97-L101), I got tests failures

![phpunit_failed](https://user-images.githubusercontent.com/364342/236607768-a6e27042-cdf4-4f65-903f-316a150b550f.png)

**Comment by llaville** [comment]
@icanhazstring I propose to fix this, as pre-requisite to a PR, to add PHPUnit annotation as follow 

```
diff --git a/tests/Integration/UnusedCommandTest.php b/tests/Integration/UnusedCommandTest.php
index 93efe40..923e30d 100644
--- a/tests/Integration/UnusedCommandTest.php
+++ b/tests/Integration/UnusedCommandTest.php
@@ -42,6 +42,7 @@ class UnusedCommandTest extends TestCase

     /**
      * @test
+     * @requires extension ds
      */
     public function itShouldNotReportExtDsAsUnused(): void
     {
@@ -57,6 +58,7 @@ class UnusedCommandTest extends TestCase

     /**
      * @test
+     * @requires extension ds
      */
     public function itShouldNoReportUnusedWithAutoloadFilesWithRequire(): void
     {
```

That will allow to get tests PASSED 

![check_ok](https://user-images.githubusercontent.com/364342/236608054-b636f164-1386-4de8-8df9-7100344e461a.png)

Are you agree ?

**Comment by llaville** [comment]
That will allow to make the extension `ds` as optional (after all it's a dev composer requirement ;-) ), and perharps need to update the  CONTRIBUTING guide too

**Comment by icanhazstring** [comment]
Sounds good. Go ahead 🙂

**Comment by llaville** [comment]
Integration tests was fixed as suggested : https://github.com/llaville/composer-unused/commit/ce5a02e25771f0fc610fd50e3bf2925604a25c91

... now will add polyfill !

**Comment by llaville** [comment]
PR #508 will close this feature
