### ISSUE TITLE
BC break in 0.8.8 "Command "default" is not defined

### ISSUE THREAD

**Issue by staabm** [composer-unused/composer-unused#514]
## Describe the bug
in rector-src CI we use `vendor/bin/composer-unused --ansi --output-format default`  to override the github default format detection

see https://github.com/rectorphp/rector-src/blob/18af399494c5de1d75db67782cad566e65b534bb/.github/workflows/code_analysis.yaml#L60-L62

it seems with the recent 0.8.8 this breaks

see e.g. https://github.com/rectorphp/rector-src/actions/runs/4957138210/jobs/8868455127?pr=3809

```
mstaab@NB-COMPLEX-61 MINGW64 /c/dvl/Workspace/rector-src-staabm (dump-container)
$ vendor/bin/composer-unused --ansi --output-format default

                                     
  Command "default" is not defined.  
                                     

```

**Comment by icanhazstring** [comment]
Thanks, checking.

**Comment by staabm** [comment]
you are right.. not sure why it worked before ;)
