### ISSUE TITLE
Error in NameContext on invalid file

### ISSUE THREAD

**Issue by erickskrauch** [composer-unused/composer-unused#518]
## Describe the bug

After updating to version `0.8.8`, the analyser began to give an error. I was able to determine that it was caused by the [plivo/php-sdk](https://github.com/plivo/plivo-php) package. In the folder `src` is the directory `Examples`, which contains examples with invalid code. [This particular one](https://github.com/plivo/plivo-php/blob/452ad6d8fffcc23810a551ea63df32ee4ee4cee4/src/Examples/Phlo.php) breaks composer-unused.

In version `0.8.7` the problem isn't reproduced, so I assume that in version `0.8.8` something has been changed about hos invalid files are handled.

The error:
```
In NameContext.php line 71:

  Cannot use Plivo\Resources\PHLO\PhloRestClient as PhloRestClient because the name is already in use on line 32
```

**Comment by MarcinGladkowski** [comment]
@erickskrauch Would you provide steps to reproduce ? In my examples this situation did't happen.

**Comment by icanhazstring** [comment]
Tried it with latest release and this seem to work now.
I will close it now, if you still encounter this issue please reopen with some way to reproduce.

Thanks :)
