### ISSUE TITLE
Error on running by documentation steps

### ISSUE THREAD

**Issue by GinoPane** [composer-unused/composer-unused#557]
## Describe the bug

Installed as a dev dependency and ran as README sugests `vendor/bin/composer-unused`

```
Fatal error: Uncaught Error: Typed property ComposerUnused\ComposerUnused\Composer\Config::$name must not be accessed before initialization in /var/www/vendor/icanhazstring/compose
r-unused/src/Composer/Config.php:26
Stack trace:
#0 /var/www/vendor/icanhazstring/composer-unused/src/Composer/PackageFactory.php(16): ComposerUnused\ComposerUnused\Composer\Config->getName()
#1 /var/www/vendor/icanhazstring/composer-unused/src/Console/Command/UnusedCommand.php(150): ComposerUnused\ComposerUnused\Composer\PackageFactory->fromConfig(Object(ComposerUnused
\ComposerUnused\Composer\Config))
#2 /var/www/vendor/symfony/console/Command/Command.php(326): ComposerUnused\ComposerUnused\Console\Command\UnusedCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput),
 Object(Symfony\Component\Console\Output\ConsoleOutput))
```

## Additional information
If you encounter environment problems, such as memory limit, provide some information
about your `php -i`

If you encounter a false-positive unused packages give some debug information:

<details>
  <summary>composer-unused debug:consumed-symbols</summary>
  ```
  <output from command>
  ```
</details>

<details>
  <summary>composer-unused debug:defined-symbols [package]</summary>
  ```
  <output from command>
  ```
</details>

**Comment by GinoPane** [comment]
Ok, the reason is that my composer.json does not have a "name". But it is not required.

**Comment by icanhazstring** [comment]
It is kind of required for composer-unused. Otherwise I can't attach additional files to a package name. So your application, which is the root package does need a name.

Maybe I need to validate that before hand to make it more clear 👍

**Comment by GinoPane** [comment]
Yep, makes sense to validate and throw readable error

**Comment by MarcinGladkowski** [comment]
@icanhazstring 

That's is simple validation for properties. Now, only for name. PR. https://github.com/composer-unused/composer-unused/pull/562

What do you think ?
