### ISSUE TITLE
False-positives for not fully imported packages

### ISSUE THREAD

**Issue by GinoPane** [composer-unused/composer-unused#558]
## Describe the bug

Package reports some packages as not used whereas they are actaully used
![image](https://github.com/composer-unused/composer-unused/assets/3897579/2d07f6c0-4d8f-4300-ba1e-8caeaf553166)

But both are actually used in Laravel project config/app.php in service providers section

![image](https://github.com/composer-unused/composer-unused/assets/3897579/707a6b84-30db-41cb-a1b5-2a8a1cf1eb57)
![image](https://github.com/composer-unused/composer-unused/assets/3897579/88c580cb-a4b7-46a4-9329-d5e30047e6d6)

**Comment by icanhazstring** [comment]
Hi thanks. Did you register these files in your config. So composer-unused can register and scan them.

If they are outside your psr-4 directive they won't be picked automatically.

**Comment by GinoPane** [comment]
Tried with a config placed in a project root

![image](https://github.com/composer-unused/composer-unused/assets/3897579/bb2eea2d-a1ef-450d-9bca-c86906bcbd5b)

**Comment by icanhazstring** [comment]
The name should not be the package, but your project. As mentioned in the other issue.

**Comment by GinoPane** [comment]
Ok, cool, now it is working:
![image](https://github.com/composer-unused/composer-unused/assets/3897579/77ef2eb9-a999-465d-a146-38159dfc91e8)

Thanks
