### ISSUE TITLE
Composer 2 support

### ISSUE THREAD

**Issue by Jean85** [composer-unused/composer-unused#76]
## Is your feature request related to a problem? Please describe
Composer is starting to roll out 2.0-dev builds: https://github.com/composer/composer/issues/8726

## Describe the solution you'd like
Support Composer 2.0 (without BC if possible), without dropping 1.0 support.

## Describe alternatives you've considered
If the above is not possible, we can plan a new major version.

**Comment by icanhazstring** [comment]
Hi @Jean85. Thanks for reaching out. I will try if there is a breaking change with the new api. If not I can simply allow it.

Also, in future the direct composer plugin will be decoupled from the actual tool.

But for now, I'll see if this is an easy fix 👍

**Comment by icanhazstring** [comment]
Hi @Jean85 

I have added support for composer 2.0. I checked it against my local setup and it runs on current snapshot version of composer. Could you please verify as well if everything is working?

You can install it as a global composer dependency using:

```
$ composer global require icanhazstring/composer-unused:dev-update-composer
$ composer unused
```

Thanks in advance 👍

**Comment by Jean85** [comment]
You can easily test yourself in CI like I did here: https://github.com/getsentry/sentry-symfony/blob/master/.travis.yml#L51-L53

I can't right now because in the projects where I use yours, I also use Symfony Flex, which is not yet compatible...

**Comment by icanhazstring** [comment]
Nice thanks for the testing idea.
Will set it up right away and see if it works :)

For symfony/flex. What is the compatibility issue?
Maybe I could help somehow?

**Comment by icanhazstring** [comment]
Merged with #77 into `dev-master`. Tag coming ASAP

**Comment by Jean85** [comment]
Flex has a pending issue: https://github.com/symfony/flex/pull/617
It's a bit complicated due to the fact that it's deeply rooted inside Composer.

**Comment by icanhazstring** [comment]
Ah. I see, so not much I can do on that front :)

**Comment by icanhazstring** [comment]
Tagged with https://github.com/composer-unused/composer-unused/tree/0.7.2
