### ISSUE TITLE
phar 0.7.2 throws a fatal error

### ISSUE THREAD

**Issue by jakzal** [composer-unused/composer-unused#82]
## Describe the bug

Running the latest phar (0.7.2) throws a fatal error.

Steps to reproduce:

```bash
curl -Ls https://github.com/composer-unused/composer-unused/releases/download/0.7.2/composer-unused.phar > composer-unused.phar
php composer-unused.phar
```

## Error dump

```
PHP Fatal error:  Uncaught Error: Class 'Composer\Console\Application' not found in phar:///Users/kuba/Projects/toolbox/cu2.phar/bin/composer-unused:39
Stack trace:
#0 phar:///Users/kuba/Projects/toolbox/cu2.phar/bin/composer-unused(52): {closure}(Array)
#1 /Users/kuba/Projects/toolbox/cu2.phar(14): require('phar:///Users/k...')
#2 {main}
  thrown in phar:///Users/kuba/Projects/toolbox/cu2.phar/bin/composer-unused on line 39
```

**Comment by icanhazstring** [comment]
Hi @jakzal thanks for reporting.
Will check it out.

**Comment by icanhazstring** [comment]
@jakzal can you give me some information about your setup?

- php version (`php -v`) 
- composer version (`composer --version`)
- your `composer.json` (you can remove proprietary informations)

Thanks.

**Comment by jakzal** [comment]
```
$ php -v
PHP 7.4.2 (cli) (built: Jan 22 2020 06:30:58) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.2, Copyright (c), by Zend Technologies
```

```
$ composer --version
Composer version 1.10.6 2020-05-06 10:28:10
```

composer.json: 

https://github.com/jakzal/toolbox/blob/6d71753cbdf5b2256d71a1a3299e7abb5b807685/composer.json#L5-L23

**Comment by JoshuaBehrens** [comment]
I can confirm. Using it from composer instead works.

**Comment by icanhazstring** [comment]
Thank you both for confirming. Fixed with #84 and will tag it soon.
I added a new workflow check to validate the phar output so this problem should not hit another version in the future 👍

**Comment by JoshuaBehrens** [comment]
Thanks for fixing :)

**Comment by icanhazstring** [comment]
Tagged `0.7.3`. Thanks for reporting 👍
