### ISSUE TITLE
icanhazstring/composer-unused usages not detected

### ISSUE THREAD

**Issue by simPod** [composer-unused/composer-unused#90]
## Describe the bug
`icanhazstring/composer-unused` is reported as unused.

## Additional information

This is to reproduce https://github.com/simPod/php-bugs/commit/d8c3b26882be05dda34d19ff1d580c3431182d0d

**Comment by icanhazstring** [comment]
Using this commit i only see `bentools/iterable-functions` not being used which is true.
And `php-64bit` not found (ignored) which should be used instead - this is a bug.

But composer-unused is not reported as unused.

**Comment by simPod** [comment]
It is used in these lines

https://github.com/simPod/php-bugs/commit/d8c3b26882be05dda34d19ff1d580c3431182d0d#diff-08174935c89921090730ea9ac6d84c52R7

https://github.com/simPod/php-bugs/commit/d8c3b26882be05dda34d19ff1d580c3431182d0d#diff-08174935c89921090730ea9ac6d84c52R13

**Comment by simPod** [comment]
https://github.com/bpolaszek/php-iterable-functions#iterable_to_array

**Comment by icanhazstring** [comment]
Ok, but anyways this is currently not possible and worked on in #89

**Comment by simPod** [comment]
Ok, I'll keep it ignored. Thx! Can close if u with.

**Comment by icanhazstring** [comment]
I will keep it open and mark is a duplicate to #85 so you can receive updated when its available :)

**Comment by icanhazstring** [comment]
Closed due to the main problem fixed in `0.8.x`
