### ISSUE TITLE
Composer virtual packages are reported as ignored

### ISSUE THREAD

**Issue by icanhazstring** [composer-unused/composer-unused#93]
## Describe the bug
Running `composer unused` in a library that requires a virtual package (e.g. `psr/log-implementation`) composer unused is obviously not able to locate the package. Packages with the `-implementation` suffix should not be reported at all.

## Additional information
https://devedge.wordpress.com/2014/09/27/composer-and-virtual-packages/
https://matthiasnoback.nl/2014/10/composer-provide-and-dependency-inversion/

As the `excludePackage` feature was added back again with #222.
This issue can utilize this implementation to actually match packages ending with `-implementation` to be ignored as well.

This could be done somewhere around here:
https://github.com/composer-unused/composer-unused/blob/main/src/Command/Handler/CollectFilteredDependenciesCommandHandler.php#L17

**Comment by icanhazstring** [comment]
related to: #217

**Comment by markuspoerschke** [comment]
I tested this bug and I get the following output:

```
❯ php vendor/bin/composer-unused


Loading packages
----------------

 4/4 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

 ! [NOTE] Found 2 package(s) to be checked.                                                                             

Scanning files from basedir /Users/markus.poerschke/Development/Keks/composer-unused-test
-----------------------------------------------------------------------------------------

 1/1 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

Results
-------

Found 0 used, 2 unused and 2 ignored packages

 Used packages

 Unused packages
 ✗ eluceo/ical
 ✗ psr/log

 Ignored packages
 ○ icanhazstring/composer-unused (Invalid package type)
 ○ psr/log-implementation (Unable to locate package)
```

My example project: https://github.com/markuspoerschke/composer-unused-test/tree/issue-93

```
git clone --branch issue-93 https://github.com/markuspoerschke/composer-unused-test.git
cd composer-unused-test
composer install
php vendor/bin/composer-unused 
```
