### ISSUE TITLE
myclabs/php-enum is marked as unused

### ISSUE THREAD

**Issue by simPod** [composer-unused/composer-unused#95]
https://github.com/myclabs/php-enum

Reproduced here https://github.com/simPod/php-bugs/tree/unused-enum

```php
<?php

declare(strict_types=1);

namespace SimPod\Bugs;

/**
 * @template T
 * @extends \MyCLabs\Enum\Enum<T>
 * @psalm-immutable
 */
abstract class Enum extends \MyCLabs\Enum\Enum
{
}
```

**Comment by icanhazstring** [comment]
Hi @simPod thanks for reporting. 

I think this is related to #94 and the `extends` keyword is not scanned.
So it's kind of a combination. Will see to it 👍

**Comment by icanhazstring** [comment]
As `extends` is not supported. `implements` might also not work.

**Comment by icanhazstring** [comment]
@simPod could you please verify using `:dev-master` if this fix works for you. If you, I will tag a new release.

**Comment by icanhazstring** [comment]
Tagged as `0.7.4`

**Comment by simPod** [comment]
Wrks, thx!
