### ISSUE TITLE
False positives for packages which are not used directly

### ISSUE THREAD

**Issue by lulco** [composer-unused/composer-unused#96]
## Describe the bug
In one of my project I use package `https://github.com/lulco/redis-proxy` which suggests usage of `predis/predis` in case you don't have `ext-redis` installed, so my composer looks like:

```
"require": {
        "lulco/redis-proxy": "^0.4.1",
        "predis/predis": "^1.1"
}
```

It is true I don't use any part of `predis/predis` directly, but I use redis-proxy which uses it. Not sure if it is correct and I have to exclude predis/predis or it is a bug :)

Thanks for your work.

**Comment by icanhazstring** [comment]
Hi @lulco

That is weird. Because I have a check which looks for suggested packages 🤔

I will a look at that. Thanks for reporting 👍

**Comment by lulco** [comment]
Hi, maybe the problem is connected with the issue that package lulco/redis-proxy uses classmap autoload and not psr?

**Comment by icanhazstring** [comment]
That could be. Since proxy-redis will be marked unused, the suggested package will not be taken into account.

So yes good catch 👍

**Comment by icanhazstring** [comment]
As soon as #89 is done. This should be solved.
As before I only relied on `psr-0` and `psr-4´ namespaces in a `composer.json` which was pretty easy to do.
So I need to rework how composer-unused scans for symbols.

**Comment by lulco** [comment]
@icanhazstring we can close this issue too. With -x option 0.8.x-dev it works
